# Generated by Django 4.1.7 on 2023-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
