# Generated by Django 4.1.7 on 2023-03-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='is_staff',
        ),
    ]
